version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: myapp_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: myappdb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - myapp-network

  web:
    build: ./web
    container_name: myapp_web
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: myappdb
    networks:
      - myapp-network
    deploy:
      replicas: 2  # Optional (use Docker Swarm for this)

volumes:
  db_data:

networks:
  myapp-network:










