version: "3.9"

services:
  web:
    build: ./webapp
    expose:
      - "8080"   # internal port for Flask
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=myappdb
    depends_on:
      - db
    deploy:
      replicas: 2

  db:
  image: mysql:8.0
  environment:
    MYSQL_ROOT_PASSWORD: rootpassword
    MYSQL_DATABASE: myappdb
  volumes:
    - db_data:/var/lib/mysql
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  nginx:
    image: nginx:alpine
    ports:
      - "5000:80"   # <--- changed from 8080 to 5000
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web

volumes:
  db_data:




