version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: dockercompose_db_1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword   # required
      MYSQL_DATABASE: myappdb             # auto-create DB
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: ./webapp
    container_name: dockercompose_web
    environment:
      DB_HOST: db
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: myappdb
    depends_on:
      - db
    ports:
      - "8080:8080"
    scale: 2

  nginx:
    image: nginx:alpine
    ports:
      - "5000:80"
    depends_on:
      - web

volumes:
  db_data:







